let quote = [
    "You cannot change what you refuse to confront.",
    "Sometimes good things fall apart so better things can fall together.",
    "Don’t think of cost. Think of value.",
    "Sometimes you need to distance yourself to see things clearly.",
    "Too many people buy things they don’t need with money they don’t have to impress people they don’t know. Read Rich Dad, Poor Dad.",
    "No matter how many mistakes you make or how slow you progress, you are still way ahead of everyone who isn’t trying.",
    "If a person wants to be a part of your life, they will make an obvious effort to do so. Think twice before reserving a space in your heart for people who do not make an effort to stay.",
    "Making one person smile can change the world – maybe not the whole world, but their world.",
    "Saying someone is ugly doesn’t make you any prettier.",
    "The only normal people you know are the ones you don’t know very well.",
    "Life is 10% of what happens to you and 90% of how you react to it.",
    "The most painful thing is losing yourself in the process of loving someone too much, and forgetting that you are special too.",
    "It’s better to be alone than to be in bad company.",
    "As we grow up, we realize it becomes less important to have more friends and more important to have real ones.",
    "Making a hundred friends is not a miracle. The miracle is to make a single friend who will stand by your side even when hundreds are against you.",
    "Giving up doesn’t always mean you’re weak, sometimes it means you are strong enough and smart enough to let go and move on.",
    "Don’t say you don’t have enough time. You have exactly the same number of hours per day that were given to Helen Keller, Pasteur, Michelangelo, Mother Teresea, Leonardo da Vinci, Thomas Jefferson, Albert Einstein, etc…",
    "If you really want to do something, you’ll find a way. If you don’t, you’ll find an excuse.",
    "Don’t choose the one who is beautiful to the world; choose the one who makes your world beautiful.",
    "Falling in love is not a choice. To stay in love is.",
    "True love isn’t about being inseparable; it’s about two people being true to each other even when they are separated.",
    "While you’re busy looking for the perfect person, you’ll probably miss the imperfect person who could make you perfectly happy.",
    "Never do something permanently foolish just because you are temporarily upset.",
    "You can learn great things from your mistakes when you aren’t busy denying them. Read The 7 Habits of Highly Effective People.",
    "In life, if you don’t risk anything, you risk everything.",
    "When you stop chasing the wrong things you give the right things a chance to catch you.",
    "Every single thing that has ever happened in your life is preparing you for a moment that is yet to come.",
    "There isn’t anything noble about being superior to another person. True nobility is in being superior to the person you once were.",
    "Trying to be someone else is a waste of the person you are.",
    "You will never become who you want to be if you keep blaming everyone else for who you are now.",
    "People are more what they hide than what they show.",
    "Sometimes people don’t notice the things others do for them until they stop doing them.",
    "Don’t listen to what people say, watch what they do.",
    "Being alone does not mean you are lonely, and being lonely does not mean you are alone.",
    "Love is not about sex, going on fancy dates, or showing off. It’s about being with a person who makes you happy in a way nobody else can.",
    "Anyone can come into your life and say how much they love you. It takes someone really special to stay in your life and show how much they love you.",
    "Burn the candles, use the nice sheets, wear the fancy lingerie. Don’t save it for a special occasion; today is special.",
    "Love and appreciate your parents. We are often so busy growing up; we forget they are also growing old.",
    "When you have to start compromising yourself and your morals for the people around you, it’s probably time to change the people around you.",
    "Learn to love yourself first, instead of loving the idea of other people loving you.",
    "When someone tells you, “You’ve changed,” it might simply be because you’ve stopped living your life their way.",
    "Someone else doesn’t have to be wrong for you to be right.",
    "Be happy. Be yourself. If others don’t like it, then let them be. Happiness is a choice. Life isn’t about pleasing everybody.",
    "When you’re up, your friends know who you are. When you’re down, you know who your friends are.",
    "Don’t look for someone who will solve all your problems; look for someone who will face them with you.",
    "If you expect the world to be fair with you because you are fair, you’re fooling yourself. That’s like expecting the lion not to eat you because you didn’t eat him.",
    "No matter how good or bad you have it, wake up each day thankful for your life. Someone somewhere else is desperately fighting for theirs.",
    "The smallest act of kindness is worth more than the grandest intention.",
    "Many people are so poor because the only thing they have is money.",
    "Learn to appreciate the things you have before time forces you appreciate the things you once had.",
    "When you choose to see the good in others, you end up finding the good in yourself.",
    "You don’t drown by falling in the water. You drown by staying there.",
    "It’s better to know and be disappointed than to never know and always wonder.",
    "There are things that we don’t want to happen but have to accept, things we don’t want to know but have to learn, and people we can’t live without but have to let go.",
    "Happiness is not determined by what’s happening around you, but rather what’s happening inside you. Most people depend on others to gain happiness, but the truth is, it always comes from within.",
    "If you tell the truth, it becomes a part of your past. If you lie, it becomes a part of your future.",
    "What you do every day matters more than what you do every once in a while. Read The Power of Habit.",
    "You can’t start the next chapter of your life if you keep re-reading your last one.",
    "Things turn out best for people who make the best out of the way things turn out.",
    "If you don’t like something, change it. If you can’t change it, change the way you think about it.",
    "You become what you focus on and like the people you spend time with.",
    "People do what seems easy and convenient, not what is best for them.",
    "When values are clear, decisions are easy.",
    "If you just help enough other people get what they need, you will get everything you need.",
    "Build your house on the rock of learning; no one can take your education away from you.",
    "Whatever you fill your brain with and whoever you spend your time with… will determine your life a decade from now.",
    "Hope is NOT a strategy.",
    "Successful people willingly do what unsuccessful people are unwilling to do.",
    "My definition of success: When your core values and self-concept are in harmony with your daily actions and behaviors.",
    "To be interesting be interested.",
    "Remember: everyone you meet is fighting a mighty battle. Be kind. Be understanding.",
    "The minute you stop expecting life to be simple, fair and easy… it becomes simple, fair and easy.",
    "To be successful in life you must have a PLAN: PREPARE for the journey – LAUNCH into action – ADJUST as you go – NETWORK with those who know."
];